version: "3.3"

services:
  database:
    container_name: cadeduque
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=root2023 #definido a senha para o banco de dados
      - POSTGRES_USER=marqueane #usuário de acesso ao banco de dados
      - POSTGRES_DB=cadeduque
    ports:
      - 5434:5432 #porta de acesso ao banco de dados